# Generated by Django 4.1.1 on 2023-01-29 10:17

import Operations.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_title', models.TextField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentication.registerpersonnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=10)),
                ('album_image_thumbnail', models.ImageField(null=True, upload_to=Operations.models.upload_to)),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Operations.album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
