# Generated by Django 4.1.1 on 2023-02-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image_url',
        ),
    ]
